package com.goldendevs.testapplication.model

data class DataResponse(
    val resultCount: Int,
    val results: List<Result>
)

data class Result(
    val artistId: Int,
    val artistName: String,
    val artistViewUrl: String,
    val artworkUrl100: String,
    val artworkUrl30: String,
    val artworkUrl60: String,
    val artworkUrl600: String,
    val collectionArtistId: Int,
    val collectionArtistViewUrl: String,
    val collectionCensoredName: String,
    val collectionExplicitness: String,
    val collectionHdPrice: Double,
    val collectionId: Int,
    val collectionName: String,
    val collectionPrice: Double,
    val collectionViewUrl: String,
    val contentAdvisoryRating: String,
    val copyright: String,
    val country: String,
    val currency: String,
    val description: String,
    val discCount: Int,
    val discNumber: Int,
    val feedUrl: String,
    val hasITunesExtras: Boolean,
    val isStreamable: Boolean,
    val kind: String,
    val longDescription: String,
    val previewUrl: String,
    val primaryGenreName: String,
    val releaseDate: String,
    val shortDescription: String,
    val trackCensoredName: String,
    val trackCount: Int,
    val trackExplicitness: String,
    val trackHdPrice: Double,
    val trackHdRentalPrice: Double,
    val trackId: Int,
    val trackName: String,
    val trackNumber: Int,
    val trackPrice: Double,
    val trackRentalPrice: Double,
    val trackTimeMillis: Int,
    val trackViewUrl: String,
    val wrapperType: String
){
    fun toMovieDetails() : MovieDetailsEntity {
        return MovieDetailsEntity(
             artistId,
         artistName,
         artistViewUrl,
         artworkUrl100,
         artworkUrl30,
         artworkUrl60,
         artworkUrl600,
         collectionArtistId,
         collectionArtistViewUrl,
         collectionCensoredName,
         collectionExplicitness,
         collectionHdPrice,
         collectionId,
         collectionName,
         collectionPrice,
         collectionViewUrl,
         contentAdvisoryRating,
         copyright,
         country,
         currency,
         description,
         discCount,
         discNumber,
         feedUrl,
         hasITunesExtras,
         isStreamable,
         kind,
         longDescription,
         previewUrl,
         primaryGenreName,
         releaseDate,
         shortDescription,
         trackCensoredName,
         trackCount,
         trackExplicitness,
         trackHdPrice,
         trackHdRentalPrice,
         trackId,
         trackName,
         trackNumber,
         trackPrice,
         trackRentalPrice,
         trackTimeMillis,
         trackViewUrl,
         wrapperType
        )
    }
}



